name: Tests

on: workflow_dispatch

jobs:
  check:
    strategy:
      fail-fast: true

    name: Forward
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Compile contracts
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests
        run: |
          forge test -vvv
        id: test
